version: "3.8"

services:
  postgres17:
    container_name: postgres17
    image: postgres:17-bookworm
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: hoppscotch
    ports:
      - "65432:5432"
    volumes:
      - <your_dir>:/var/lib/postgresql/data
    networks:
      hoppscotch-network:
        ipv4_address: 172.228.0.2
    restart: always

#  hoppscotch:
#    container_name: hoppscotch
#    restart: always
#    depends_on:
#      postgres:
#        condition: service_started
#    image: hoppscotch/hoppscotch:latest
#    ports:
#      - "3000:3000"
#      - "3100:3100"
#      - "3170:3170"
#    env_file:
#      - ./local.env
##    network_mode: "host"
#    networks:
#      hoppscotch-network:
#        ipv4_address: 172.228.0.3
  hoppscotch-frontend:
    image: hoppscotch/hoppscotch-frontend
    depends_on:
      hoppscotch-backend:
        condition: service_started
    ports:
      - "3000:3000"
    env_file:
      - local.env
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  hoppscotch-backend:
      image: hoppscotch/hoppscotch-backend
      depends_on:
          postgres17:
            condition: service_started
      ports:
        - "3170:3170"
      env_file:
        - local.env
      restart: always
      extra_hosts:
        - "host.docker.internal:host-gateway"
      networks:
          hoppscotch-network:
            ipv4_address: 172.228.0.50
  
  proxyscotch:
    image: hoppscotch/proxyscotch:v0.1.3
    environment:
      - PROXYSCOTCH_ALLOWED_ORIGINS=127.0.0.1
#      - PROXYSCOTCH_BANNED_OUTPUTS=<banned_outputs>
#      - PROXYSCOTCH_BANNED_DESTS=<banned_dests>
    ports:
      - "9159:9159"
networks:
  hoppscotch-network:
    ipam:
      config:
        - subnet: 172.228.0.0/24
